### ISSUE TITLE
API fails -> silent error

### ISSUE THREAD

**Issue by styts** [tezbox/tezbox-chrome-plugin#1]
`https://tezrpc.me/api/blocks/head` currently returns `Error` as the response.

When I try to create a new wallet, it silently fails - because the response can not be parsed.

Expecting a user friendly error message instead.

**Comment by stephenandrews** [comment]
Currently tezrpc is down due to repeated ddos attacks. Will be available once I setup cloudflare

**Comment by stephenandrews** [comment]
Fixed - new RPC api etc
