### ISSUE TITLE
Restore from seed functionality doesn't work.

### ISSUE THREAD

**Issue by edubai** [tezbox/tezbox-chrome-plugin#3]
Hello,

Can you test the Restore from seed button? It doesn't work as intended.

Thanks

**Comment by stephenandrews** [comment]
This now works on the latest version - thanks!

**Comment by shaun19826** [comment]
@edubai Hello, are you still having this issue or it’s been resolved ?

**Comment by edubai** [comment]
> @edubai Hello, are you still having this issue or it’s been resolved ?

@shaun19826 Hi there, I don’t remember, I guess I moved to Galleon wallet to restore my Tez wallet.
https://cryptonomic.tech/galleon.html
After that just move into hardware wallet like ledger, much safer, good luck.
