### ISSUE TITLE
Hello sir, Issue on create account

### ISSUE THREAD

**Issue by calmesriram** [tezbox/tezbox-chrome-plugin#6]
I have installed tezbox extension in my  chrome browser when i have opened and i choosen Tezbox create account to create account . It shows to enter password new and repeated in the textbox. after entering password it messages ERROR

Is there any solution ?

**Comment by stephenandrews** [comment]
We will be releasing the next version shortly - thanks!

**Comment by stephenandrews** [comment]
This should be resolved now - thanks
